"""
Data models for the Recovery Manager system.
Follows the CUBE Buildathon Recovery Manager specification.
"""

from enum import Enum
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from datetime import datetime, timezone


class ManagerType(str, Enum):
    RECEIVING = "Receiving Manager"
    PREP = "Prep Manager"
    PACK = "Pack Manager"
    SHIPPING = "Shipping Manager"
    RETURNS = "Returns Manager"
    PLATFORM_BILLING = "Platform Billing"
    UNKNOWN = "Unknown Manager"


class AssessmentType(str, Enum):
    CONTRADICTED = "CONTRADICTED"      # Evidence disproves the charge -> Defensible claim
    SUPPORTED = "SUPPORTED"            # Evidence confirms the charge -> Legitimate charge, no claim
    SILENT = "SILENT"                  # No relevant evidence found -> Insufficient evidence, no claim
    UNCERTAIN = "UNCERTAIN"            # Ambiguous/conflicting/partial evidence -> Inconclusive, conservative
    DUPLICATE = "DUPLICATE"            # Same fee billed multiple times -> Defensible duplicate claim
    ALREADY_REIMBURSED = "ALREADY_REIMBURSED"  # Concession/credit already granted -> No claim


class ClaimStatus(str, Enum):
    ACTIONABLE = "ACTIONABLE"          # Ready to file dispute
    NOT_SUPPORTED = "NOT_SUPPORTED"    # Cannot file dispute
    INCONCLUSIVE = "INCONCLUSIVE"      # Needs human review or further data
    RESOLVED = "RESOLVED"              # Already reimbursed


# Ingested Fee Charge
class FeeCharge(BaseModel):
    charge_id: str = Field(..., description="Unique charge identifier (e.g. 48291)")
    org_id: Optional[str] = Field(None, description="Multi-tenancy organization ID")
    shipment_id: Optional[str] = Field(None, description="Shipment reference (e.g. SHP-10291)")
    order_id: Optional[str] = Field(None, description="Order reference")
    sku: Optional[str] = Field(None, description="Product SKU or ASIN")
    unit_id: Optional[str] = Field(None, description="Specific unit serial/item barcode")
    fee_type: str = Field(..., description="Type of fee or penalty (e.g. Packaging defect, Labeling, Weight discrepancy)")
    reason_description: Optional[str] = Field(None, description="Raw explanation provided on the fee report")
    amount: float = Field(..., description="Amount charged in USD or local currency")
    currency: str = Field("USD", description="Currency symbol/code")
    charge_date: Optional[str] = Field(None, description="Date or timestamp the charge appeared")
    source_report: Optional[str] = Field(None, description="Filename or report ID")


# Ingested Reimbursement Record
class ReimbursementRecord(BaseModel):
    reimbursement_id: str = Field(..., description="Unique reimbursement transaction ID")
    org_id: Optional[str] = Field(None, description="Multi-tenancy organization ID")
    original_charge_id: Optional[str] = Field(None, description="Referenced charge ID if explicitly linked")
    shipment_id: Optional[str] = Field(None, description="Shipment reference")
    order_id: Optional[str] = Field(None, description="Order reference")
    sku: Optional[str] = Field(None, description="Product SKU or ASIN")
    amount_reimbursed: float = Field(..., description="Amount already credited back")
    currency: str = Field("USD", description="Currency")
    date_processed: Optional[str] = Field(None, description="Date credited")
    reason: Optional[str] = Field(None, description="Reimbursement note or category")


# Operational Evidence Record generated by upstream managers
class OperationalEvidence(BaseModel):
    evidence_id: str = Field(..., description="Unique evidence record ID")
    org_id: Optional[str] = Field(None, description="Multi-tenancy organization ID")
    manager: ManagerType = Field(..., description="Manager generating this evidence record")
    shipment_id: Optional[str] = Field(None, description="Associated shipment ID")
    order_id: Optional[str] = Field(None, description="Associated order ID")
    sku: Optional[str] = Field(None, description="Associated SKU or ASIN")
    unit_id: Optional[str] = Field(None, description="Associated Unit ID")
    timestamp: str = Field(..., description="ISO or readable timestamp when logged")
    activity: str = Field(..., description="Operational action (e.g., Inbound Inspection, Barcode Labeling, Box Weighing)")
    check_type: str = Field(..., description="Category of check (e.g., packaging, labeling, weight, dimension, seal)")
    status: str = Field(..., description="Outcome: PASS, FAIL, COMPLIANT, NON_COMPLIANT, DAMAGED, INTACT")
    details: Dict[str, Any] = Field(default_factory=dict, description="Structured metrics, e.g. measured_weight_lbs, barcode_value, box_condition")
    media_references: List[str] = Field(default_factory=list, description="IDs or paths to captured records/photographs")
    notes: Optional[str] = Field(None, description="Operator or automated system notes")


# Evidence Match Link
class EvidenceMatch(BaseModel):
    evidence: OperationalEvidence
    relevance_score: float = Field(..., description="Score 0.0 to 1.0 indicating match strength")
    match_aspect: str = Field(..., description="Aspect matched: e.g. packaging compliance, weight verification")
    is_contradictory: bool = Field(False, description="True if evidence disproves fee")
    is_supporting: bool = Field(False, description="True if evidence confirms fee")
    is_ambiguous: bool = Field(False, description="True if evidence has conflicting signals")
    rationale: str = Field(..., description="Clear explanation of the correlation")


# Single Charge Assessment Result
class RecoveryResult(BaseModel):
    charge: FeeCharge
    assessment: AssessmentType
    claim_status: ClaimStatus
    potential_claim_amount: float = Field(0.0, description="Amount eligible for recovery")
    supporting_evidence: List[EvidenceMatch] = Field(default_factory=list, description="Operational records backing the dispute or verification")
    claim_rationale: str = Field(..., description="Defensible legal/commercial explanation")
    evidence_traceability: List[str] = Field(default_factory=list, description="IDs and timestamps of operational records used")
    confidence: float = Field(..., description="Confidence score 0.0 - 1.0")
    recommendation: str = Field(..., description="Action recommendation for operator")


# Complete Recovery Analysis Dossier
class RecoveryDossier(BaseModel):
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    total_charges_evaluated: int
    total_fee_amount: float
    total_potential_recovery: float
    total_supported_fees: float
    total_silent_or_inconclusive: float
    total_already_reimbursed: float
    results: List[RecoveryResult]
    audit_notes: List[str] = Field(default_factory=list)
